// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynCawi3-q-v0oztKnzJH-c9A14TUEcaM',
    appId: '1:967207010981:web:f07452079c0ba5aeba834c',
    messagingSenderId: '967207010981',
    projectId: 'flutter-student-manageme-3391a',
    authDomain: 'flutter-student-manageme-3391a.firebaseapp.com',
    storageBucket: 'flutter-student-manageme-3391a.appspot.com',
    measurementId: 'G-Z4M0R4RZWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6rTd-bXE2U0qiZJNXvcoEr0IZcDYEOs',
    appId: '1:967207010981:android:81819d9c87e06adfba834c',
    messagingSenderId: '967207010981',
    projectId: 'flutter-student-manageme-3391a',
    storageBucket: 'flutter-student-manageme-3391a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1XlXtxUmTvRUs-oWqPu3eYCAYG2o5zU',
    appId: '1:967207010981:ios:78b2387fff27c55cba834c',
    messagingSenderId: '967207010981',
    projectId: 'flutter-student-manageme-3391a',
    storageBucket: 'flutter-student-manageme-3391a.appspot.com',
    iosBundleId: 'com.example.flutterStudentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd1XlXtxUmTvRUs-oWqPu3eYCAYG2o5zU',
    appId: '1:967207010981:ios:36bc15297888bb29ba834c',
    messagingSenderId: '967207010981',
    projectId: 'flutter-student-manageme-3391a',
    storageBucket: 'flutter-student-manageme-3391a.appspot.com',
    iosBundleId: 'com.example.flutterStudentManagement.RunnerTests',
  );
}
